name: Push component to https://components.espressif.com
on:
  push:
    tags:
      - v*
jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Upload component to the component registry
        uses: espressif/upload-components-ci-action@v1
        with:
          name: "lvgl_esp32_drivers"
          version: ${{ github.ref_name }}
          namespace: "vitoralho"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
